---
title: Acknowledgments
---
The CVA2.0 project is funded by the Inflation Reduction Act. 

This project would not have been possible without the dedication and hardwork of countless individuals aboard the federal and state-run survey programs and the NOAA Observer program. 

Many thanks to the following state-run programs for contributing data:

* [Northeast Area Monitoring and Assessment Program Nearshore Trawl](https://www.neamap.net/neamap-nearshore-trawl/)
* [Maine-New Hampshire Inshore Trawl Survey](https://www.neamap.net/menh-inshore-trawl/)
* [Massachusetts Division of Marine Fisheries Bottom Trawl Survey](https://www.neamap.net/madmf-bottom-trawl/)
* [Long Island Sound Trawl Survey](https://portal.ct.gov/deep/fishing/fisheries-management/long-island-sound-trawl-survey)
* [New York Nearshore Trawl Survey](https://www.neamap.net/ny-nearshore-trawl/)
* [New Jersey Ocean Stock Assessment Survey](https://dep.nj.gov/njfw/fishing/marine/ocean-stock-assessment-program/#:~:text=The%20New%20Jersey%20Ocean%20Stock,times%20throughout%20a%20calendar%20year.)
* [Delaware Trawl Surveys](https://dnrec.delaware.gov/fish-wildlife/fishing/research/)

We also thank all of the NOAA staff, members of the New England and Mid Atlantic Fisheries Management Councils, the Atlantic States Marine Fisheries Commission, and our academic partners for their feedback and assistance in developing the methods described here. 

This website is based on the tutorial by Openscapes [quarto-website-tutorial](https://github.com/Openscapes/quarto-website-tutorial) by Julia Lowndes and Stefanie Butland.
