#' @title Build Prediction Data Frame
#' @description Match test data to model prediction rasters in a data.frame. Used to calculate AUC in \code{calculate_sdm_auc} and \code{ensemble_sdm_wrapper.R}
#'
#' @param observations a data.frame. A data.frame including fisheries observations.
#' @param xy_col a vector with a length of 2 indicating the longitude and latitude column names
#' @param prediction_rasters spatRaster of predicted model values on desired timeseries. Values will be matched to observations in \code{data}.

build_preds_df <- function(observations, xy_col, prediction_rasters){
  names(prediction_rasters) <- paste0("predicted_", names(prediction_rasters))

  #step 1 - extract the unique locations within data
  unique_locs_df <- unique(observations[, c("gridID", xy_col)])
  unique_locs_v  <- terra::vect(unique_locs_df, geom = xy_col, crs = "EPSG:4326")

  # Extract everything in one single spatial pass
  extracted_wide <- terra::extract(prediction_rasters, unique_locs_v, ID = TRUE)

  # Merge the spatial IDs back with your location metadata
  extracted_wide_meta <- cbind(unique_locs_df, extracted_wide)

  # 2 Reshape from wide to long format using base R's reshape()
  # This looks for the "_" delimiter we created in step 1
  extracted_long <- stats::reshape(
    extracted_wide_meta,
    idvar = c("gridID", xy_col, "ID"), # Columns that uniquely identify the location
    varying = 5:ncol(extracted_wide_meta),    # The columns containing the extracted raster data
    direction = "long",
    sep = "_",                                # Splits "predicted_7.2026" into time and variable
    timevar = "month.year"                     # Name of the new time column
  )

  # Clean up rownames generated by reshape()
  rownames(extracted_long) <- NULL

  # 5. Merge the results back into your original observation data.frame
  preds <- merge(
    observations,
    extracted_long[, c("gridID", "month.year", "predicted")],
    by = c("gridID", "month.year"),
    all.x = TRUE
  )

  preds <- preds[stats::complete.cases(preds),]

  return(preds)
}
