# This file suppresses NOTEs about "no visible binding for global variable"
# during R CMD check.

utils::globalVariables(c(
  # Column names / Tidy evaluation variables
  "Attribute.Name",
  "imp",
  "mod",
  "dfC",
  "ev",
  "staticVars",
  "bathyR",
  'ens',
  'mapExp',
  'vecExp',
  'totalM',
  'totalT',
  'cW',
  'abund',
  'expRanked',
  "Scoring.Rank1",
  'Scoring.Rank2',
  'Scoring.Rank3',
  'Scoring.Rank4',
  'A',
  'B',
  'C',
  'D',
  'p',
  'dist_chart',
  'y',
  'v',
  'Factor.Name',
  'Mean.x',
  'Mean.y',
  'Std.Dev..x',
  'Std.Dev..y',
  'mean_time',
  'sd_time',
  'dist_time',
  'mean_space',
  'sd_space',
  'dist_space',
  # Operators from other packages
  ".",
  "%>%",
  "%do%",
  "%dopar%"
))
