#' @title Make Exposure Summary Table
#' @description
#' Generates the summary exposure table with final factor scores, standard deviations, and distribution of spatial and temporal for each species, as well as final exposure scores. One table is generated per species and saved in the species folder. Requires directory to be set up per directions in the package documentation/manual.
#'
#' @param species names of the species to plot. Must match folder name to pull correct data and save table correctly.
#' @param present_time,future_time character strings indicating the present and future time series to compare. Example: '1993-2019'. Used to pull correct calculations and save the data properly
#' @param variable_df a data.frame containing all possible environmental variables, such as from the MOM6 model. Must contain columns \code{Long.Name} and \code{Short.Name}, containing the full names and abbreviated names of the variables. Abbreviated names should correspond to those in the weights vector produced by \code{normalize_variable_weights}
#' @param model_metrics a data.table containing the model evaluation metrics for each species. Generated by \code{make_evaluation_csv}.
#' @param auc_col name of the column containing the AUC values to be included in the table footnote
#' @param model_confidence a data.table containing the model confidence scores for each species.
#'
#' @return Function does not return anything. The table is saved to species- and timeframe-specific \code{figures} folder. See manual for directory set up.

make_exposure_table <- function(species, present_time, future_time, variable_df, model_metrics, auc_col, model_confidence){

  for(s in species){

    #### this section is currently untested
    #pull metrics
    #auc
    mod.auc <- model_metrics[which(model_metrics$Common.Name == s),auc_col]

    #model_confidence
    mc.mean <- model_confidence[which(model_confidence$Species == s), 'meanConfidence']
    mc.sd <- model_confidence[which(model_confidence$Species == s), 'sdConfidence']
    ####

    ###load data for each species
    #load variable weights
    load(paste0(file.path(getwd(),s, 'Data'), '/combined_variable_weights.RData')) #cW

    ####TIMESERIES
    #load timeseries
    load(paste0(file.path(getwd(),s, 'Data'), '/', present_time, ' vs ', future_time, '/variable_exposure_timeseries.RData')) #vecExp
    #subset timeseries matrix by rownames
    i <- rownames(vecExp) %in% names(cW)
    vecSub <- vecExp[i,]

    #load total exposure timeseries - all vars
    load(paste0(file.path(getwd(),s, 'Data'), '/', present_time, ' vs ', future_time, '/total_exposure_timeseries_all.RData')) #totalT
    totalAll <- totalT

    #load total exposure timeseries - important vars
    load(paste0(file.path(getwd(),s, 'Data'), '/', present_time, ' vs ', future_time, '/total_exposure_timeseries_subset.RData')) #totalT
    totalImp <- totalT

    ##create means and standard deviations
    allMean <- mean(totalAll, na.rm = T)
    allSD <- sd(totalAll, na.rm = T)
    impMean <- mean(totalImp, na.rm = T)
    impSD <- sd(totalImp, na.rm = T)
    timeMean <- c(apply(vecSub, 1, FUN = mean, na.rm = T), allMean, impMean)
    timeSD <- c(apply(vecSub, 1, FUN = sd, na.rm =T), allSD, impSD)
    names(timeMean)[(length(timeMean)-1):length(timeMean)] <- names(timeSD)[(length(timeSD)-1):length(timeSD)] <- c('expAll', 'expImp')

    #make summary table
    timeTab <- as.data.frame(cbind(timeMean, timeSD))
    timeTab <- round(timeTab, 2)
    #clean up
    timeTab$Factor.Name <- rownames(timeTab)
    rownames(timeTab) <- NULL
    timeTab <- timeTab[,c(3,1,2)]
    colnames(timeTab)[2:3] <- c("Mean", 'Std.Dev.')

    for(x in 1:(nrow(timeTab)-2)){
      timeTab$Factor.Name[x] <- variable_df$Long.Name[which(variable_df$Short.Name == timeTab$Factor.Name[x])]
    }
    timeTab$Factor.Name[nrow(timeTab)-1] <- 'Exposure - All Variables'
    timeTab$Factor.Name[nrow(timeTab)] <- 'Exposure - Important Variables'

    #make plots
    #add totals
    vecSub <- rbind(vecSub, totalAll, totalImp)
    vecSub <- as.data.frame(vecSub)
    # 1. Convert rows of the matrix/df into a list of vectors
    row_list <- split(as.matrix(vecSub), seq_len(nrow(vecSub)))
    # 2. Use map to build the plots
    plot_dist_time <- purrr::map(row_list, function(row_vals) {
      # Create a data frame for the row
      df <- data.frame(v = row_vals)

      ggplot2::ggplot(df, ggplot2::aes(x = v, fill = ggplot2::after_stat(x))) +
        ggplot2::geom_histogram(
          breaks = seq(0.5, 4.5, by = 1), # Force exactly 4 bins at 1, 2, 3, 4
          color = "grey25",
          linewidth = 4,
          show.legend = FALSE
        ) +
        # Map your 4 specific colors to the 4 x-axis positions
        ggplot2::scale_fill_gradientn(
          colors = c("green", "yellow", "orange", "red"),
          guide = "none"
        ) +
        ggplot2::scale_x_continuous(limits = c(0.5, 4.5)) +
        ggplot2::theme_void()+
        ggplot2::theme(
          plot.margin = ggplot2::margin(0, 0, 0, 0) # Remove all internal ggplot whitespace
        )
    })

    ##### MAPS
    #load maps
    load(paste0(file.path(getwd(),s, 'Data'), '/', present_time, ' vs ', future_time, '/variable_exposure_maps.RData')) #mapExp
    #subset timeseries matrix by rownames
    i <- names(mapExp) %in% names(cW)
    mapSub <- raster::subset(mapExp, which(i == T))

    #load total exposure maps - all vars
    load(paste0(file.path(getwd(),s, 'Data'), '/', present_time, ' vs ', future_time, '/total_exposure_maps_all.RData')) #totalM
    totalAll <- totalM

    #load total exposure maps - important vars
    load(paste0(file.path(getwd(),s, 'Data'), '/', present_time, ' vs ', future_time, '/total_exposure_maps_subset.RData')) #totalM
    totalImp <- totalM

    ##create means and standard deviations
    allMean <- mean(totalAll[], na.rm = T)
    allSD <- sd(totalAll[], na.rm = T)
    impMean <- mean(totalImp[], na.rm = T)
    impSD <- sd(totalImp[], na.rm = T)

    spaceMean <- spaceSD <- vector(length = raster::nlayers(mapSub))
    for(x in 1:raster::nlayers(mapSub)){
      spaceMean[x] <- mean(raster::subset(mapSub, x)[], na.rm = T)
      spaceSD[x] <- sd(raster::subset(mapSub, x)[], na.rm = T)
    }
    names(spaceMean) <- names(spaceSD) <- names(mapSub)
    spaceMean <- c(spaceMean, allMean, impMean)
    spaceSD <- c(spaceSD, allSD, impSD)
    names(spaceMean)[(length(spaceMean)-1):length(spaceMean)] <- names(spaceSD)[(length(spaceSD)-1):length(spaceSD)] <- c('expAll', 'expImp')

    #make summary table
    spaceTab <- as.data.frame(cbind(spaceMean, spaceSD))
    spaceTab <- round(spaceTab, 2)
    #clean up
    spaceTab$Factor.Name <- rownames(spaceTab)
    rownames(spaceTab) <- NULL
    spaceTab <- spaceTab[,c(3,1,2)]
    colnames(spaceTab)[2:3] <- c("Mean", 'Std.Dev.')

    for(x in 1:(nrow(spaceTab)-2)){
      spaceTab$Factor.Name[x] <- variable_df$Long.Name[which(variable_df$Short.Name == spaceTab$Factor.Name[x])]
    }
    spaceTab$Factor.Name[nrow(spaceTab)-1] <- 'Exposure - All Variables'
    spaceTab$Factor.Name[nrow(spaceTab)] <- 'Exposure - Important Variables'

    #make plots
    #add totals
    rast_list <- as.list(mapSub, totalAll, totalImp)
    plot_dist_rast <- purrr::map(rast_list, function(lyr) {
      # Extract values from each raster layer
      vals <- lyr[]

      ggplot2::ggplot(data.frame(v = vals), ggplot2::aes(x = v, fill = ggplot2::after_stat(x))) +
        ggplot2::geom_histogram(
          breaks = seq(0.5, 4.5, by = 1), # Force exactly 4 bins at 1, 2, 3, 4
          color = "grey25",
          linewidth = 4,
          show.legend = FALSE
        ) +
        # Map your 4 specific colors to the 4 x-axis positions
        ggplot2::scale_fill_gradientn(
          colors = c("green", "yellow", "orange", "red"),
          guide = "none"
        ) +
        ggplot2::scale_x_continuous(limits = c(0.5, 4.5)) +
        ggplot2::theme_void() +
        ggplot2::theme(
          plot.margin = ggplot2::margin(0, 0, 0, 0) # Remove all internal ggplot whitespace
        )
    })

    #####COMBINE
    #combine tables with placeholders for plots
    tabAll <- dplyr::left_join(timeTab, spaceTab, by = "Factor.Name") %>%
      dplyr::transmute(
        Factor.Name,
        mean_time = Mean.x, # Rename while selecting for clarity
        sd_time = Std.Dev..x,
        # Placeholders for our plots
        dist_time = "", # We'll create these in mutate below
        mean_space = Mean.y,
        sd_space = Std.Dev..y,
        dist_space = ""
      )

    ##determine which variables are important (weight > 0.1)
    is_important <- c(cW >= 0.1, FALSE, TRUE) #pad with FALSE (all vars) and TRUE (important vars) values at the end for the total Exposure variables

    # 2. Render the table
    summary.table <- tabAll %>%
      gt::gt() %>%
      #first we make it pretty
      gt::tab_header(
        title = "Exposure"
      ) %>%
      gt::tab_options(
        data_row.padding = gt::px(1)       # force minimal padding between rows
      ) %>%
      # Center all text columns
      gt::cols_align(
        align = "center",
        columns = gt::everything()
      ) %>%
      #force plot columns to be bottom aligned
      # Force a specific width so the aspect ratio calculates the height correctly
      gt::cols_width(
        Factor.Name ~ gt::px(150),                    # Give the labels enough room
        gt::starts_with("mean") ~ gt::px(60),          # Forces all Mean columns to 80px
        gt::starts_with("sd") ~ gt::px(60),            # Forces all SD columns to 80px
        gt::starts_with("dist") ~ gt::px(120)
      ) %>%
      gt::tab_options(
        heading.padding = gt::px(2),      # Tightens space around title
        column_labels.padding = gt::px(2) # Tightens space around Mean/SD labels
      ) %>%
      gt::tab_style(
        style = "vertical-align: bottom !important; line-height: 0; padding-bottom: 0;",
        locations = gt::cells_body(columns = gt::starts_with("dist"))
      ) %>%
      gt::tab_style(
        style = "line-height: 0; padding: 0;", # CSS to remove text-based 'float'
        locations = gt::cells_body(columns = colnames(tabAll)[-1])
      ) %>%
      # make total exposure rows bold and grey
      gt::tab_style(
        style = list(
          gt::cell_fill(color = "grey75"),
          gt::cell_text(weight = "bold")
        ),
        locations = gt::cells_body(rows = c(nrow(tabAll)-1, nrow(tabAll)))
      ) %>%
      # highlight the important variables
      gt::tab_style(
        style = list(
          gt::cell_text(style = "italic", color = "darkblue")
        ),
        locations = gt::cells_body(rows = is_important == TRUE)
      ) %>%
      # Add a thick horizontal line above the Total Exposure row
      gt::tab_style(
        style = gt::cell_borders(
          sides = "top",
          color = "black",
          weight = gt::px(4)
        ),
        locations = gt::cells_body(rows = c(nrow(tabAll)-1))
      ) %>%
      #add "headers" (aka spanners) to distinguish time/space columns
      gt::tab_spanner(
        label = "Time",
        columns = c(mean_time, sd_time, dist_time)
      ) %>%
      gt::tab_spanner(
        label = "Space",
        columns = c(mean_space, sd_space, dist_space)
      ) %>%
      #change line style of columns
      #thick borders to distinguish factor names and time/space sections
      gt::tab_style(
        style = gt::cell_borders(
          sides = "right",
          color = "black",
          weight = gt::px(2)
        ),
        locations = gt::cells_body(columns = c('Factor.Name', 'dist_time', 'dist_space'))
      ) %>%
      #thinner lines everywhere else
      gt::tab_style(
        style = gt::cell_borders(
          sides = "right",
          color = "grey25",
          weight = gt::px(1)
        ),
        locations = gt::cells_body(columns = c('mean_time', 'sd_time', 'mean_space', 'sd_space'))
      ) %>%
      #make the column labels pretty
      gt::cols_label(
        Factor.Name = "Factor Name",
        mean_time = "Mean",
        sd_time = "SD",
        dist_time = "Distribution",
        mean_space = "Mean",
        sd_space = "SD",
        dist_space = "Distribution"
      ) %>%
      #Now we add the plots
      # Apply the Table Plots to the 4th column
      gt::text_transform(
        locations = gt::cells_body(columns = dist_time),
        fn = function(x) {
          # Increase the height here to px(80) to fill the cell
          plots <- purrr::map(plot_dist_time, gt::ggplot_image, height = gt::px(40), aspect_ratio = 2.5)

          # Wrap EACH plot in a bottom-aligned flex container
          purrr::map(plots, ~gt::html(as.character(paste0(
            "<div style='display: flex; flex-direction: column; justify-content: flex-end; align-items: center; height: 42px;'>",
            .x,
            "</div>"
          ))))
        }
      ) %>%
      # Apply the Raster Plots to the 7th column
      gt::text_transform(
        locations = gt::cells_body(columns = dist_space),
        fn = function(x) {
          # Increase the height here to px(80) to fill the cell
          plots <- purrr::map(plot_dist_rast, gt::ggplot_image, height = gt::px(40), aspect_ratio = 2.5)

          # Wrap EACH plot in a bottom-aligned flex container
          purrr::map(plots, ~gt::html(as.character(paste0(
            "<div style='display: flex; flex-direction: column; justify-content: flex-end; align-items: center; height: 42;'>",
            .x,
            "</div>"
          ))))
        }
      ) %>%
      #Ensure the vertical-align is still bottom
      gt::tab_style(
        style = "vertical-align: bottom !important; padding-top: 2px; padding-bottom: 0px;",
        locations = gt::cells_body(columns = gt::starts_with("dist"))
      ) %>%
      ##add footer with model confidence score and AUC
      gt::tab_source_note(
        source_note = gt::html(paste0(
          "<div style='text-align: center; font-size: 18px; width: 100%; font-weight: bold;'>",
          "Model Confidence: ", mc.mean, " ( SD:", mc.sd, ") | AUC: ", round(mod.auc,2), "</div>"
        ))
      ) %>%
      #add box
      gt::tab_options(
        # Sets a border around the entire table container
        table.border.top.style = "solid",
        table.border.top.width = gt::px(4),
        table.border.top.color = "black",

        table.border.bottom.style = "solid",
        table.border.bottom.width = gt::px(4),
        table.border.bottom.color = "black",

        # These two add the side borders to complete the box
        table.background.color = "white",
        table.additional_css = "
        .gt_table {
          border-left: 4px solid black !important;
          border-right: 4px solid black !important;
        }"
      )

    #Save
    gt::gtsave(summary.table, paste0(file.path(getwd(),s, 'Figures'), '/', present_time, ' vs ', future_time, '/exposure_summary_table.pdf'))

  } #end s

}
