#' @title Render Species Distribution Model (SDM) reports
#' @description
#' Builds SDM report using a provided template. Requires directory to be set up per directions in the package documentation/manual.
#'
#' @param species.list a data.table containing the species names. Must contain the column \code{Common.name}
#' @param yrStart,yrEnd start and end of timeseries to plot, used to pick correct model predictions to include
#' @param model.metrics a data.table containing the model metrics for each species. Generated by \code{model.metrics}.
#' @param feeding_key,habitat_key file path to csv for feeding and habitat guild keys respectively. Used for matching variable names. See vignette for recommended set up of these files.
#' @param variable_key a data.frame containing all possible modeled variables, such as from the MOM6 model. Must contain columns \code{Long.Name} and \code{Short.Name}, containing the full names and abbreviated names of the variables. Abbreviated names should correspond to those in the variable importance plots
#' @param template a character string designating the .qmd file to use as a template
#' @param report.path character string designating where the reports should be saved
#'
#' @return Function does not return anything. Reports are saved to \code{report.path}

makereport_sdms <- function(species.list, yrStart, yrEnd, model.metrics, feeding_key, habitat_key, variable_key, template, report.path){
  #create 'clean' names
  species.list$Name <- gsub(' ', '', species.list$Common.Name)

  for (i in 1:nrow(species.list)) {

    # Extract the current row as a list
    row <- species.list[i, ]

    message(paste("Currently rendering:", row$Common.Name))

    # Clean species name for file paths (e.g., "Blue Whale" -> "Blue_Whale")
    clean_name <- row$Name

    #match to metrics
    mrow <- model.metrics[which(model.metrics$Common.Name == row$Common.Name),]

    ##get list of variables from guilds
    fList <- feeding_key[,which(names(feeding_key) == row$Feeding.Guild)]
    fTab <- variable_key[variable_key$Short.Name %in% fList,]
    hList <- habitat_key[,which(names(habitat_key) == row$Habitat.Guild)]
    hTab <- variable_key[variable_key$Short.Name %in% hList,]
    #fhTab <- c(fTab, hTab)

    # 3. Render the report
    quarto::quarto_render(
      input = template,
      output_file = paste0("SDM_Report_", clean_name, ".pdf"),
      execute_params = list(
        species_name = row$Common.Name,
        fGuild = row$Feeding.Guild,
        hGuild = row$Habitat.Guild,
        fTab = as.data.frame(fTab),
        hTab = as.data.frame(hTab),
        n_pres       = mrow$N.PRESENCE,
        n_abs        = mrow$N.ABSENCE,
        aucWI          = round(mrow$ENS.AUC, digits = 3),
        aucOUT = round(mrow$AUC.2020.2023, digits = 3),
        # Assuming your PDFs follow a naming convention:
        weight_plot_pdf = paste0(file.path(getwd(),clean_name, 'figures'), '/component_model_weights.pdf'),
        imp_plot_pdf = paste0(file.path(getwd(),clean_name, 'figures'), '/variable_importance_radars.pdf'),
        results_pdf  = paste0(file.path(getwd(),clean_name, 'figures'), '/mean_SDM_', yrStart, '_', yrEnd, '_vert.pdf'),
        resid_hist    = paste0(file.path(getwd(),clean_name, 'figures'), '/histogram_residuals_' , yrStart, '_', yrEnd, '.pdf'),
        resid_map    = paste0(file.path(getwd(),clean_name, 'figures'), '/mean_residuals_', yrStart, '_', yrEnd, '.pdf')
      )
    )

    #move to final folder
    file.rename(
      from = paste0("SDM_Report_", clean_name, ".pdf"),
      to = file.path(report.path, paste0("SDM_Report_", clean_name, ".pdf"))
    )
  } #end i


} #end function
