#' @title Make Plots for Species Distribution Models
#' @description
#' Produces plots necessary for SDM reports. Requires directory to be set up per directions in the package documentation/manual.
#'
#' @param species name of the species to plot. Must match folder name to pull correct data and save figures correctly.
#' @param type at least one of the following: 'ensemble', 'weights', 'importance', 'residuals'. Used to determine what to plot.
#' @param source 'hindcast' or 'forecast' to determine which MOM6 data to pull
#' @param release release code for MOM6 data. Helps pull correct model projections associated with the MOM6 data with the same name
#' @param spatial_temporal TRUE/FALSE to determine method for normalizing. Helps pull correct model projections associated with the MOM6 data with the same name
#' @param mask_bathy TRUE/FALSE indicating whether or not bathymetry data was used as a mask for raw data before normalization. Helps pull correct model projections associated with the MOM6 data with the same name
#' @param rm_corr TRUE/FALSE indicating whether or not correlated environmental covariates were removed. Helps to pull correct model projections
#' @param var_names character vector containing possible variable names. matched against names in data.frame for variable importance extraction. should include both dynamic (environmental) and static (geographical) names. 
#' @param coastline shapefile used to plot land in model prediction plots
#' @param model_metrics a data.table containing the model metrics for each species. Generated by \code{make_evaluation_csv}.
#' @return Function does not return anything. Figures are saved to species-specific \code{figures} folder.
#'
#'@export

make_sdm_plots <- function(
  species,
  type = c('ensemble', 'weights', 'importance', 'residuals'),
  release, spatial_temporal, mask_bathy, rm_corr,
  var_names,
  coastline,
  model_metrics
) {
  #determine what to plot
  ind <- c('ensemble', 'weights', 'importance', 'residuals') %in% type
  #this produces a vector of TRUE/FALSES determining what to plot. 
  
  #suffixes to help locate correct data
  suffix <- if(spatial_temporal) "" else "_global"
  bathy_suffix <- if(mask_bathy) "masked" else ""
  corr_suffix <- if(rm_corr) "rmcorr" else ""

  for (s in species) {
    message(paste0("Plotting SDM Plots for ", s, "..."))

    # Define standard paths
    spp_dir        <- file.path(getwd(), s)
    
    if (ind[1]) {
      message(paste("Plotting Ensemble SDM..."))
      #plot ensemble model results
      predictions_path <- file.path(spp_dir, 'output_rasters', paste0('ENSEMBLE_', source, '_', release, '_', bathy_suffix, suffix, '.tif'))
      abund <- terra::rast(predictions_path)

      #avg ensemble HSM
      avgHSM <- terra::tapp(abund, index = rep(1:12, times = terra::nlyr(abund)/12), fun = 'mean') #average by month => assuming a monthly timeseries 
      names(avgHSM) <- month.abb

      grDevices::pdf(
        paste0(
          file.path(spp_dir, 'figures'),
          '/mean_SDM_',
          release,
          '.pdf'
        ),
        width = 8,
        height = 11
      )
      graphics::par(mfrow = c(4, 3), mar = c(3, 3, 1, 0))
      for (y in 1:12) {
        terra::plot(
          avgHSM[[y]],
          range = c(0, 1),
          col = cmocean::cmocean('matter')(64),
          legend = F,
          pax = list(cex.axis = 2, cex.lab = 1.25,
                     yat = seq(35,45,by=1),
                     retro = T),
          mar = c(3.1, 3.1, 2.1, 2.1), # Remove outer right margin space
          xlab = '', 
          ylab = ''
        )
        plot(coastline, col = 'grey', add = T)
        graphics::legend('topleft', bty = 'n', legend = month.abb[y], cex = 2)
      }
      fields::image.plot(
        matrix(seq(0, 1, by = 0.1), 11, 11),
        legend.only = T,
        horizontal = T,
        legend.shrink = 0.7,
        smallplot = c(0.4, 0.8, 0.25, 0.35),
        legend.args = list(
          text = 'Probability of\nOccurance',
          cex = 0.75,
          side = 3,
          line = 0.1
        ),
        axis.args = list(cex.axis = 1, mgp = c(3, 0.5, 0)),
        col = cmocean::cmocean('matter')(64)
      )
      grDevices::dev.off()
    } #end sdm results

    if (ind[2]) {
      message(paste("Plotting component model weights & AUC..."))

      #create 'clean' names
      model_metrics$Name <- gsub(' ', '', model_metrics$Common.Name)

      #make model weight barplots
      m <- as.matrix(model_metrics[which(model_metrics$Name == s), paste(c("BRT", 'GAM', 'MAXENT', 'RF', 'SDMTMB'), "WT", sep = '.')])
      grDevices::pdf(
        paste0(
          file.path(spp_dir, 'figures'),
          '/component_model_weights.pdf'
        ),
        width = 6,
        height = 6
      )
      graphics::barplot(
        m,
        names = c("BRT", 'GAM', 'MAXENT', 'RF', 'SDMTMB'),
        ylab = 'Weight',
        xlab = 'Component Model',
        ylim = c(0, 0.3)
      )
      graphics::box()
      grDevices::dev.off()

      aucs <- as.matrix(model_metrics[which(model_metrics$Name == s), c("BRT", 'GAM', 'MAXENT', 'RF', 'SDMTMB')])
      grDevices::pdf(
        paste0(file.path(spp_dir, 'figures'), '/component_model_aucs.pdf'),
        width = 6,
        height = 6
      )
      graphics::barplot(
        aucs,
        names = c("BRT", 'GAM', 'MAXENT', 'RF', 'SDMTMB'),
        ylab = 'AUC',
        xlab = 'Component Model',
        ylim = c(0, 1)
      )
      graphics::box()
      grDevices::dev.off()
    } #end weights

    if (ind[3]) {
      message(paste("Plotting variable importance..."))
      #make radar importance plots
      training_name <- file.path(spp_dir, paste0('training_', training_years[1], '_', training_years[2], '_', corr_suffix, '_hindcast_', release, '_', bathy_suffix, suffix, '.csv'))
      
      if (!file.exists(training_name)) {
        message("Data file missing.")
        return(NULL) # Exit function gracefully
      }
      
      dfT <- read.csv(file.path(training_name)) 
      
      flist <- dir(
        file.path(spp_dir, 'model_output/importance'),
        full.names = T, 
        pattern = 'rds'
      )
      flistClean <- dir(
        file.path(spp_dir, 'model_output/importance'),
        full.names = F, 
        pattern = 'rds'
      )

      #set up data frame
      vars <- names(dfT)[names(dfT) %in% var_names]
      v <- data.frame(var = vars)

      for (x in 1:length(flist)) {
        load(flist[x]) #imp
        if (inherits(imp, 'data.frame') & grepl('BRT', flist[x])) {
          v <- merge(v, imp, by = 'var', all.x = T)
        }
        if (inherits(imp, 'data.frame') & grepl('SDMTMB', flist[x])) {
          v <- merge(v, imp[,1:2], by.x = 'var', by.y = 'Variable')
        } 
        if(!inherits(imp, 'data.frame')){
          imp.df <- data.frame(var = names(imp)[!is.na(names(imp))], var.imp = imp[!is.na(names(imp))])
          v <- merge(v, imp.df, by = 'var', all.x = T)
        }
        #print(x)
      }

      colnames(v)[-1] <- gsub('.rds', '', flistClean)

      v <- replace(v, is.na(v), 0)

      dfI <- t(apply(v[,-1], 2, FUN = function(x) {
        x / sum(x)
      }))
      colnames(dfI) <- v$var

      dfI <- rbind(rep(max(dfI, na.rm = T), ncol(dfI)), rep(0, ncol(dfI)), dfI)

      pal <- RColorBrewer::brewer.pal(n = 5, 'Set1')

      grDevices::pdf(
        paste0(
          file.path(spp_dir, 'figures'),
          '/variable_importance_radars.pdf'
        ),
        width = 8,
        height = 11
      )
      graphics::par(mfrow = c(2, 1), mar = c(1, 4, 1, 4))
      fmsb::radarchart(
        as.data.frame(dfI),
        pfcol = scales::alpha(pal, 0.1),
        pty = 15:19,
        pcol = scales::alpha(pal, 1),
        plty = 1,
        title = "Component Models",
        vlcex = 1.25
      )
      graphics::legend(
        'topleft',
        legend = rownames(dfI)[3:7],
        lty = 1,
        col = pal,
        pch = 15:19,
        bty = 'n'
      )
      #}
      #add weighted mean from ensemble
      load(file.path(spp_dir, 'model_output/ensemble_weights.rds')) #weights 
      dfW <- dfI[-c(1, 2), ]
      ws <- apply(dfW, MARGIN = 2, FUN = weighted.mean, w = weights, na.rm = T)
      ws <- rbind(dfI[1:2, ], ws)
      fmsb::radarchart(
        as.data.frame(ws),
        pfcol = scales::alpha(pal, 0.5),
        pty = 19,
        pcol = scales::alpha(pal, 1),
        plty = 1,
        title = 'ENSEMBLE',
        vlcex = 1.25
      )
      grDevices::dev.off()
    } #end variable importance plots

    if (ind[4]) {
      message(paste("Plotting residuals..."))
      #residual plots
      #model predictions
      predictions_path <- file.path(spp_dir, 'output_rasters', paste0('ENSEMBLE_', source, '_', release, '_', bathy_suffix, suffix, '.tif'))
      abund <- terra::rast(prediction_path)

      #observations
      obs_name <- file.path(spp_dir, paste0('fisheries_environment', '_', corr_suffix, '_hindcast_', release, '_', bathy_suffix, suffix, '.csv'))
      obs <- read.csv(obs_name)

      preds <- build_preds_df(obs, xy_col = c("grid.lon", "grid.lat"), abund)

      preds$residuals <- preds$pa - preds$predicted

      template_r <- abund[[1]][[1]]
      #avg residuals
      avgR <- vector(mode = 'list', length = 12)
      for (y in 1:12) {
        sub <- preds[preds$month == y,]
        pts <- terra::vect(sub, geom=c("grid.lon", "grid.lat"), crs = 'EPSG:4326')
        avgR[[y]] <- terra::rasterize(pts, template_r, field = 'residuals', fun = mean)
      } #end for
      avgR <- terra::rast(avgR)
      names(avgR) <- month.abb

      grDevices::pdf(
        paste0(
          file.path(spp_dir, 'figures'),
          '/mean_residuals_',
          release,
          '.pdf'
        ),
        width = 8,
        height = 11
      )
      graphics::par(mfrow = c(4, 3), mar = c(3, 3, 1, 0))
      for (y in 1:12) {
        terra::plot(
          avgR[[y]],
          range = c(-1, 1),
          col = cmocean::cmocean('balance')(64),
          legend = F,
          pax = list(cex.axis = 2, cex.lab = 1.25,
                     yat = seq(35,45,by=1),
                     retro = T),
          mar = c(3.1, 3.1, 2.1, 2.1), # Remove outer right margin space
          xlab = '', 
          ylab = ''
        )
        plot(coastline, col = 'grey', add = T)
        graphics::legend('topleft', bty = 'n', legend = month.abb[y], cex = 2)
      }
      fields::image.plot(
        matrix(seq(-1, 1, by = 0.1), 11, 11),
        legend.only = T,
        horizontal = T,
        legend.shrink = 0.7,
        smallplot = c(0.4, 0.8, 0.25, 0.35),
        legend.args = list(
          text = 'Residuals',
          cex = 0.75,
          side = 3,
          line = 0.1
        ),
        axis.args = list(cex.axis = 1, mgp = c(3, 0.5, 0)),
        col = cmocean::cmocean('balance')(64)
      )
      grDevices::dev.off()

      grDevices::pdf(
        paste0(
          file.path(spp_dir, 'figures'),
          '/histogram_residuals_',
          release,
          '.pdf'
        ),
        width = 6,
        height = 6
      )
      graphics::hist(preds$residuals, main = '', xlab = 'Residuals')
      grDevices::dev.off()

      rm(abund, obs) #clear out large data objects to help with looping
    } #end residuals
  }
}
