#' @title Make Exposure Summary Table
#' @description
#' Generates the summary exposure table with final factor scores, standard deviations, and distribution of spatial and temporal for each species, as well as final exposure scores. One table is generated per species and saved in the species folder. Requires directory to be set up per directions in the package documentation/manual.
#'
#' @param species names of the species to plot. Must match folder name to pull correct data.
#' @param forecast_release,hindcast_release MOM6 release codes for the (f)orecast and (h)indcasts used. Used to pull correct variable exposures
#' @param forecast_init forecast_initialization code corresponding to the forecast_initalization date of the desired forecast data. Used to pull correct variable exposures
#' @param hindcast_yr_range character string corresponding to the years in the hindcast data used. Used to pull correct ranked exposure values and save the data properly
#' @param variable_df a data.frame containing all possible environmental variables, such as from the MOM6 model. Must contain columns \code{Long.Name} and \code{Short.Name}, containing the full names and abbreviated names of the variables. Abbreviated names should correspond to those in the weights vector produced by \code{normalize_variable_weights}
#' @param model_metrics a data.table containing the model evaluation metrics for each species. Generated by \code{make_evaluation_csv}.
#' @param auc_col name of the column containing the AUC values to be included in the table footnote
#' @param model_confidence a data.table containing the model confidence scores for each species.
#' @param table_dir file path to folder to save tables in
#'
#' @return Function does not return anything. The table is saved as a png to the \code{table_dir} folder. 
#'
#'@export

make_exposure_table <- function(
  species,
  forecast_release,
  forecast_init,
  hindcast_release,
  hindcast_yr_range,
  variable_df,
  stock_key,
  table_dir
  #model_metrics,
 # auc_col,
  #model_confidence
) {
  
  attribute_names_clean <- c(variable_df$Long.Name, 'Total Exposure - All Variables', "Total Exposure - Important Variables")
  attribute_names_raw <-  c(variable_df$Short.Name, 'totalAll', 'totalImp')
  
  attr_map <- setNames(attribute_names_clean, 
                      attribute_names_raw)
  
  for (s in species) {
    
    #### this section is currently untested
    #pull metrics
    #auc
   # mod.auc <- model_metrics[which(model_metrics$Common.Name == s), auc_col]

   # #model_confidence
  #  mc.mean <- model_confidence[
   #   which(model_confidence$Species == s),
  #    'meanConfidence'
   # ]
  #mc.sd <- model_confidence[
   #   which(model_confidence$Species == s),
    #  'sdConfidence'
  #  ]
    ####

    ###load data for each species
    #load variable weights
    var_imp <- readRDS(paste0(
      file.path(here::here('Exposure'), s, 'Data'),
      '/normalized_dynamic_variable_importance.rds'
    )) #cW
    
    var_imp_nms <- colnames(var_imp)[var_imp[nrow(var_imp),] >= 0.1]
    
    #load stocks if available
    if (file.exists(paste0('../shpfiles/species_stock_areas/', s, '.shp'))) {
      stocks <- terra::vect(paste0(
        '../shpfiles/species_stock_areas/',
        s,
        '.shp'
      )) 
    } else {
      stocks <- NULL
    }

    #load maps
    #variable exposure 
    varExp <- terra::rast(paste0(
      file.path(here::here('Exposure'), s, 'Data'),
      paste0(
        '/variable_exposure_maps_',
        forecast_release,
        '_',
        forecast_init,
        '_',
        hindcast_release,
        '_',
        hindcast_yr_range,
        '.tif'
      )
    )) 

    #load total exposure maps - all vars
    totAll <- terra::rast(paste0(
      file.path(here::here('Exposure'), s, 'Data'),
      paste0(
        '/total_exposure_map_all_var_',
        forecast_release,
        '_',
        forecast_init,
        '_',
        hindcast_release,
        '_',
        hindcast_yr_range,
        '.tif'
      )
    )) 

    #load total exposure maps - important vars
    totImp <- terra::rast(paste0(
      file.path(here::here('Exposure'), s, 'Data'),
      paste0(
        '/total_exposure_map_imp_var_',
        forecast_release,
        '_',
        forecast_init,
        '_',
        hindcast_release,
        '_',
        hindcast_yr_range,
        '.tif'
      )
    )) 
    
    #stack all rasters 
    rastStack <- c(varExp, totAll, totImp)
    nl <- terra::nlyr(rastStack)
    names(rastStack)[(nl-1):nl] <- c('totalAll', 'totalImp')

    ##load means and standard deviations 
    rastMeans <- readRDS(paste0(
      file.path(here::here('Exposure'), s, 'Data'),
      paste0(
        '/total_exposure_map_averages_',
        forecast_release,
        '_',
        forecast_init,
        '_',
        hindcast_release,
        '_',
        hindcast_yr_range,
        '.rds'
      )
    )
    )   
    
    rastSD <- readRDS(paste0(
      file.path(here::here('Exposure'), s, 'Data'),
      paste0(
        '/total_exposure_map_stdevs_',
        forecast_release,
        '_',
        forecast_init,
        '_',
        hindcast_release,
        '_',
        hindcast_yr_range,
        '.rds'
      )
    )
    )

    # 2. Extract raster pixels within each stock polygon
    if(!is.null(stocks)){
      # This returns a dataframe with 'ID' (polygon index) and one column per raster layer
      ext_vals <- terra::extract(rastStack, stocks)
      
      # Map the polygon ID back to the actual stock names
      ext_vals$stock <- stocks$stock_area[ext_vals$ID]
      ext_vals$ID <- NULL
      
      #extract all pixels 
      global_vals <- as.data.frame(terra::values(rastStack))
      global_vals$stock <- 'global'
      
      all_vals <- dplyr::bind_rows(ext_vals, global_vals)
    } else {
      all_vals <- as.data.frame(terra::values(rastStack))
      all_vals$stock <- 'global'
      
      #if stocks is null, this will also mean that rastMeans/SD is missing a stocks column
      rastMeans <- as.data.frame(rastMeans)
      rastMeans$stock <- 'global'
      rastSD <- as.data.frame(rastSD)
      rastSD$stock <- 'global'
    }

    # 3. Generate categorized bar charts for continuous raster data
    plot_data <- all_vals %>%
      tidyr::pivot_longer(
        cols = dplyr::any_of(attribute_names_raw),
        names_to = "Attribute.Raw",
        values_to = "pixel_value"
      ) %>%
      dplyr::filter(!is.na(pixel_value)) %>%
      dplyr::group_by(Attribute.Raw, !!rlang::sym('stock')) %>%
      dplyr::summarise(
        p = list(
          data.frame(x = pixel_value) %>%
            # Bin the continuous pixels into 4 categories 
            dplyr::mutate(
              cat = cut(
                x, 
                breaks = c(-Inf, 1.5, 2.5, 3.5, Inf), 
                labels = c("A", "B", "C", "D")
              )
            ) %>%
            ggplot2::ggplot(ggplot2::aes(x = cat, fill = cat)) +
            ggplot2::geom_bar(show.legend = FALSE, width = 0.95, color = 'grey25', linewidth = 0.5) +
            # Use a named vector and drop = FALSE to lock the colors to the correct bars
            ggplot2::scale_fill_manual(
              values = c("A" = "green", "B" = "yellow", "C" = "orange", "D" = "red"),
              drop = FALSE 
            ) +
            # Ensures all 4 categories always appear on the x-axis, even if empty
            ggplot2::scale_x_discrete(drop = FALSE) + 
            ggplot2::theme_void() +
            ggplot2::theme(plot.margin = ggplot2::margin(0, 0, 0, 0))
        ),
        .groups = "drop"
      ) %>%
      dplyr::mutate(Attribute.Name = attr_map[Attribute.Raw])
    
    # 4. Pivot Exposure Means and DQ to Long Format
    spMeans_long <- rastMeans %>%
      dplyr::select(!!rlang::sym('stock'), dplyr::any_of(attribute_names_raw)) %>% # Changed
      tidyr::pivot_longer(
        cols = dplyr::any_of(attribute_names_raw), # Changed
        names_to = "Attribute.Raw",
        values_to = "expert.scores"
      ) %>%
      dplyr::mutate(expert.scores = round(as.numeric(expert.scores), 2))
    
    spDQ_long <- rastSD %>%
      dplyr::select(!!rlang::sym('stock'), dplyr::any_of(attribute_names_raw)) %>% # Changed
      tidyr::pivot_longer(
        cols = dplyr::any_of(attribute_names_raw), # Changed
        names_to = "Attribute.Raw",
        values_to = "data_quality"
      ) %>%
      dplyr::mutate(data_quality = round(as.numeric(data_quality), 2))
    
    # 5. Join into Final Summary Table and Pivot WIDER
    tab_wide <- spMeans_long %>%
      dplyr::left_join(spDQ_long, by = c('stock', "Attribute.Raw")) %>%
      dplyr::mutate(Attribute.Name = attr_map[Attribute.Raw]) %>%
      dplyr::left_join(plot_data, by = c("Attribute.Name", 'stock', "Attribute.Raw")) %>%
      dplyr::mutate(Attribute.Name = factor(Attribute.Name, levels = attribute_names_clean)) %>%
      dplyr::select(Attribute.Name, !!rlang::sym('stock'), expert.scores, data_quality, p) %>%
      tidyr::pivot_wider(
        names_from = dplyr::all_of('stock'),
        values_from = c(expert.scores, data_quality, p),
        names_glue = paste0("{.value}_{", 'stock', "}")
      ) %>%
      dplyr::arrange(Attribute.Name)
    
    # 5.5 Extract plot list-columns to avoid 'gt' conversion error
    plot_cols <- grep("^p_", colnames(tab_wide), value = TRUE)
    plot_list_wide <- list()
    for (p_col in plot_cols) {
      plot_list_wide[[p_col]] <- tab_wide[[p_col]] 
      tab_wide[[p_col]] <- "" 
    }
    
    # (Section 5.6 is deleted. Move straight to Section 6: Initialize gt table)
    
    # 6. Initialize gt table
    # 1. Filter the exact list that aligns with your TRUE/FALSE vector
    important_raw_names <- attribute_names_raw %in% var_imp_nms
    
    # 2. Translate those specific raw names into their clean display names
    important_clean_names <- attr_map[important_raw_names]
    
    # 3. Append the exact string of your bottom row so it also becomes italic
    important_clean_names <- c(important_clean_names, "Total Exposure - Important Variables")
    
    summary.table <- gt::gt(tab_wide) %>%
      gt::tab_header(title = 'Exposure') %>%
      gt::opt_row_striping() %>%
      gt::cols_align(align = "center", columns = gt::everything()) %>%
      gt::cols_align(align = "left", columns = c("Attribute.Name"))
    
    # Dynamically add spanners for each stock present
    stock_nms <- unique(rastMeans$stock)
    for (k in stock_nms) {
      
      # If a species has no stocks (NA or empty string), skip the spanner entirely
      if (is.na(k) || k == "" || k == "None") next 
      
      # Translate the abbreviation if it exists in the map; otherwise use the original string
      display_name <- ifelse(k %in% names(stock_key), stock_key[[k]], k)
      
      wrapped_label <- stringr::str_replace_all(
        stringr::str_wrap(display_name, width = 15), 
        pattern = "\n", 
        replacement = "  \n"
      )
      
      summary.table <- summary.table %>%
        gt::tab_spanner(
          label = gt::md(wrapped_label),
          columns = gt::ends_with(as.character(k))
        )
    }
    
    # 7. Apply styling, column renaming, and rendering
    summary.table <- summary.table %>%
      # Clean up the Attribute Name header
      gt::cols_label(
        Attribute.Name = "Attribute Name"
      ) %>%
      # Rename grouped columns
      gt::cols_label_with(
        columns = gt::starts_with("expert.scores"),
        fn = ~ "Mean"
      ) %>%
      gt::cols_label_with(
        columns = gt::starts_with("data_quality"),
        fn = ~ "SD"
      ) %>%
      gt::cols_label_with(
        columns = gt::starts_with("p_"),
        fn = ~ "Tally"
      ) %>%
      # Force text wrapping by constraining column widths
      gt::cols_width(
        Attribute.Name ~ gt::px(220), 
        gt::starts_with("expert.scores") ~ gt::px(45),
        gt::starts_with("data_quality") ~ gt::px(45),
        gt::starts_with("p_") ~ gt::px(50) # Reduced from 90
      ) %>%
      # Make all column headers and spanners bold
      gt::tab_style(
        style = gt::cell_text(weight = "bold"),
        locations = list(
          gt::cells_column_labels(),
          gt::cells_column_spanners()
        )
      ) %>%
      # Add thin bottom border to stock spanners
      gt::tab_style(
        style = gt::cell_borders(sides = "bottom", color = "black", weight = gt::px(1)),
        locations = gt::cells_column_spanners()
      ) %>%
      # Add thick vertical borders to separate stocks
      gt::tab_style(
        style = gt::cell_borders(sides = "left", color = "black", weight = gt::px(2)),
        locations = gt::cells_body(columns = gt::starts_with("expert.scores"))
      ) 
    # STOP HERE - NO PIPE (%>%) BEFORE THE FOR LOOP
    
    # Inject plots column by column 
    for (p_col in plot_cols) {
      summary.table <- local({
        col_name <- p_col
        summary.table %>%
          gt::text_transform(
            locations = gt::cells_body(columns = dplyr::all_of(col_name)),
            fn = function(x) {
              purrr::map(plot_list_wide[[col_name]], function(p) {
                
                # Failsafe: If the plot is NA or missing, return a blank space instead of crashing
                if (is.null(p) || (is.logical(p) && is.na(p[1]))) return("") 
                
                gt::ggplot_image(p, height = gt::px(15), aspect_ratio = 3)
              })
            }
          )
      })
    }
    
    # Resume the pipe chain for final table options
    summary.table <- summary.table %>%
      # 1. Add thick line to separate the main attributes from the total rows
      gt::tab_style(
        style = gt::cell_borders(sides = "top", color = "black", weight = gt::px(2)),
        locations = gt::cells_body(rows = nrow(tab_wide) - 1) # Targets the second-to-last row
      ) %>%
      # 2. Make BOTH total rows bold
      gt::tab_style(
        style = gt::cell_text(weight = "bold"),
        locations = gt::cells_body(rows = (nrow(tab_wide) - 1):nrow(tab_wide)) # Targets both bottom rows
      ) %>%
      # Italicize the important attribute names and the important total row
      gt::tab_style(
        style = gt::cell_text(style = "italic"),
        locations = gt::cells_body(
          columns = Attribute.Name,
          rows = Attribute.Name %in% important_clean_names
        )
      ) %>%
      # (Keep the rest of your gt::tab_options pipeline here exactly as it is)
      # Compress padding, center title, and set landscape layout
      gt::tab_options(
        heading.align = "center",
        table.font.size = gt::px(10), 
        data_row.padding = gt::px(2), 
        heading.padding = gt::px(2),
        column_labels.padding = gt::px(2),
        row.striping.background_color = "#D3D3D3",
        table.border.top.style = "solid",
        table.border.top.width = gt::px(2),
        table.border.top.color = "black",
        table.border.bottom.style = "solid",
        table.border.bottom.width = gt::px(2),
        table.border.bottom.color = "black",
        table.additional_css = "@page { size: landscape; margin: 0.5in; }"
      ) %>%
      gt::opt_table_lines(extent = "none")
    
    # 8. Save as a cropped, high-res image
    gt::gtsave(
      summary.table,
      paste0(table_dir, '/exposure_table_', gsub(' ', '', s), '.png'),
      vwidth = 1500 # Gives it a wide, high-resolution rendering
    )
  } #end s
}
