#' @title Make Plots for and render Species Distribution Model (SDM) reports
#' @description
#' Produces plots necessary for SDM reports used to help experts quantify model confidence and build the report using a provided template. Requires directory to be set up per directions in the package documentation/manual.
#'
#' @param species.list a data.table containing the species names. Must contain the column \code{Common.name}
#' @param plot TRUE/FALSE designating whether plots need to be made; can set to FALSE if plots already exist in figures folder
#' @param coastline shapefile used to plot land in model prediction plots
#' @param bathy raster file of bathymetry data, used to help mask off deeper predictions
#' @param yrStart,yrEnd start and end of timeseries to plot, used to pick correct model predictions
#' @param model.metrics a data.table containing the model metrics for each species. Generated by \code{model.metrics}.
#' @param feeding_key,habitat_key file path to csv for feeding and habitat guild keys respectively. Used for matching variable names. See vignette for recommended set up of these files.
#' @param variable_key a data.frame containing all possible modeled variables, such as from the MOM6 model. Must contain columns \code{Long.Name} and \code{Short.Name}, containing the full names and abbreviated names of the variables. Abbreviated names should correspond to those in the variable importance plots
#' @param template a character string designating the .qmd file to use as a template
#' @param report.path character string designating where the reports should be saved
#'
#' @return Function does not return anything. Figures are saved to species-specific \code{figures} folder. Reports are saved to \code{report.path}

plot_report_sdms <- function(species.list, plot = T, coastline, bathy, yrStart, yrEnd, model.metrics, feeding_key, habitat_key, variable_key, template, report.path){
  #create 'clean' names
  species.list$Name <- gsub(' ', '', species.list$Common.Name)

  #make plots if necessary
  if(plot){
    message(paste("Making plots..."))

    #plot ensemble model results
    for(x in 1:nrow(species.list)){
      load(paste0(getwd(), '/', species.list$Name[x], '/output_rasters/ENSEMBLE_', yrStart, '_', yrEnd, '.RData')) #abund

      #avg ensemble HSM
      avgHSM <- vector(mode = 'list', length = 12)
      for(y in 1:12){
        mn <- seq(y, length(abund), by = 12)
        MNS <- raster::stack(abund[mn])
        avgHSM[[y]] <- raster::calc(MNS, fun = mean, na.rm = T)
      } #end for
      avgHSM <- raster::stack(avgHSM)
      names(avgHSM) <- month.abb

      avgHSM <- replace(avgHSM, abs(bathy) > 1000, NA)

      pdf(paste0(file.path(getwd(),species.list$Name[x], 'figures'), '/mean_SDM_', yrStart, '_', yrEnd, '.pdf'), width = 8, height = 11)
      par(mfrow=c(4,3), mar = c(3,3,1,0))
      for(y in 1:12){
        plot(raster::subset(avgHSM, y), zlim = c(0,1), col = cmocean::cmocean('matter')(64), legend = F)
        plot(coastline['id'], col = 'grey', add = T)
        legend('topleft', bty = 'n', legend = month.abb[y], cex = 2)
      }
      fields::image.plot(matrix(seq(0,1,by = 0.1), 11,11), legend.only = T, horizontal = T, legend.shrink = 0.7,
                 smallplot = c(0.4, 0.8, 0.25, 0.35),
                 legend.args = list(text = 'Probability of\nOccurance', cex = 0.75, side = 3, line = 0.1),
                 axis.args = list(cex.axis =1, mgp = c(3, 0.5, 0)), col = cmocean::cmocean('matter')(64))
      dev.off()
    } #end sdm results

    #make model weight barplots
    for(x in 1:nrow(species.list)){

      m <- as.matrix(model.metrics[x, c(12:16)])
      pdf(paste0(file.path(getwd(),species.list$Name[x], 'figures'), '/component_model_weights.pdf'), width = 6, height = 6)
      barplot(m, names = c("BRT", 'GAM', 'MAXENT', 'RF', 'SDMTMB'), ylab = 'Weight', xlab = 'Component Model', ylim = c(0, 0.3))
      box()
      dev.off()

      aucs <- as.matrix(model.metrics[x, c(7:11)])
      pdf(paste0(file.path(getwd(),species.list$Name[x], 'figures'), '/component_model_aucs.pdf'), width = 6, height = 6)
      barplot(aucs, names = c("BRT", 'GAM', 'MAXENT', 'RF', 'SDMTMB'), ylab = 'AUC', xlab = 'Component Model', ylim = c(0, 1))
      box()
      dev.off()

      print(x)
      # print(m)
    }

    #make radar importance plots
    for(s in 1:nrow(species.list)){
      load(paste0(getwd(), '/', species.list$Name[s],'/pa_clean.RData')) #dfC
      flist <- dir(paste0(getwd(), '/', species.list$Name[s], '/model_output/importance'), full.names = T)
      flistClean <- dir(paste0(getwd(), '/', species.list$Name[s], '/model_output/importance/'), full.names = F)

      #set up data frame
      vars <- names(dfC)[-c(1:3)]
      dfI <- as.data.frame(matrix(nrow = length(flist), ncol = length(vars)))
      colnames(dfI) <- vars

      for(x in 1:length(flist)){
        load(flist[x]) #imp
        if(inherits(imp,'data.frame')){
          imp.vec <- imp$rel.inf ### need to remove spatial variables
          names(imp.vec) <- imp$var
          for(y in 1:length(names(imp.vec))){
            if(names(imp.vec)[y] %in% vars){
              i <- which(vars == names(imp.vec)[y])
              dfI[x,i] <- imp.vec[y]
            }
          }
        } else {
          for(y in 1:length(names(imp))){
            if(names(imp)[y] %in% vars){
              i <- which(vars == names(imp)[y])
              dfI[x,i] <- imp[y]
            }
          }
        }
        #print(x)
      }

      rownames(dfI) <- gsub('.RData', '', flistClean)

      dfI <- replace(dfI, is.na(dfI), 0)

      dfI <- t(apply(dfI, 1, FUN = function(x){x/sum(x)}))

      dfI <- rbind(rep(max(dfI,na.rm = T), ncol(dfI)), rep(0, ncol(dfI)), dfI)

      pal <- RColorBrewer::brewer.pal(n = 5, 'Set1')

      pdf(paste0(file.path(getwd(),species.list$Name[s], 'figures'), '/variable_importance_radars.pdf'), width = 8, height = 11)
      par(mfrow=c(2,1), mar = c(1,4,1,4))
      #for(x in 3:nrow(dfI)){
      fmsb::radarchart(as.data.frame(dfI), pfcol = scales::alpha(pal, 0.1), pty = 15:19, pcol = scales::alpha(pal, 1), plty = 1, title = "Component Models", vlcex = 1.25)
      legend('topleft', legend = rownames(dfI)[3:7], lty = 1, col = pal, pch = 15:19, bty = 'n')
      #}
      #add weighted mean from ensemble
      load(paste0(getwd(), '/', species.list$Name[s], '/model_output/ensemble_weights.RData'))
      dfW <- dfI[-c(1,2), ]
      ws <- apply(dfW, MARGIN = 2, FUN = weighted.mean, w = weights, na.rm = T)
      ws <- rbind(dfI[1:2,], ws)
      fmsb::radarchart(as.data.frame(ws), pfcol = scales::alpha(pal, 0.5), pty = 19, pcol = scales::alpha(pal, 1), plty = 1, title = 'ENSEMBLE', vlcex = 1.25)
      dev.off()
    } #end variable importance plots

    #residual plots
    ##### residuals
    #contemporary
    for(x in 1:nrow(species.list)){
      #model predictions
      load(paste0(getwd(), '/', species.list$Name[x], '/output_rasters/ENSEMBLE_', yrStart, '_', yrEnd, '.RData')) #abund
      abund <- raster::stack(abund)

      #observations
      obs <- raster::stack(paste0(getwd(), '/', species.list$Name[x], '/input_rasters/combined_rasters_', yrStart, '_', yrEnd, '.nc'))

      #manipulate obs a bit to clean it up
      names(obs) <- names(abund)
      obsC <- raster::crop(obs, raster::extent(abund))
      obsC[obsC == 0] <- NA
      obsC[obsC == 1] <- 0
      obsC[obsC == 2] <- 1

      resids <- obsC - abund

      #avg residuals
      avgR <- vector(mode = 'list', length = 12)
      for(y in 1:12){
        mn <- seq(y, raster::nlayers(resids), by = 12)
        MNS <- raster::subset(resids, mn)
        avgR[[y]] <- raster::calc(MNS, fun = mean, na.rm = T)
      } #end for
      avgR <- raster::stack(avgR)
      names(avgR) <- month.abb

      pdf(paste0(file.path(getwd(),species.list$Name[x], 'figures'), '/mean_residuals_', yrStart, '_', yrEnd, '.pdf'), width = 8, height = 11)
      par(mfrow=c(4,3), mar = c(3,3,1,0))
      for(y in 1:12){
        plot(raster::subset(avgR, y), zlim = c(-1,1), col = cmocean::cmocean('balance')(64), legend = F)
        plot(coastline['id'], col = 'grey', add = T)
        legend('topleft', bty = 'n', legend = month.abb[y], cex = 2)
      }
      fields::image.plot(matrix(seq(-1,1,by = 0.1), 11,11), legend.only = T, horizontal = T, legend.shrink = 0.7,
                 smallplot = c(0.4, 0.8, 0.25, 0.35),
                 legend.args = list(text = 'Residuals', cex = 0.75, side = 3, line = 0.1),
                 axis.args = list(cex.axis =1, mgp = c(3, 0.5, 0)), col = cmocean::cmocean('balance')(64))
      dev.off()

      pdf(paste0(file.path(getwd(),species.list$Name[x], 'figures'), '/histogram_residuals_', yrStart, '_', yrEnd, '.pdf'), width = 6, height = 6)
      hist(resids[], main = '', xlab = 'Residuals')
      dev.off()

      print(x)
    }

  } #end if plot

  for (i in 1:nrow(species.list)) {

    # Extract the current row as a list
    row <- species.list[i, ]

    message(paste("Currently rendering:", row$Common.Name))

    # Clean species name for file paths (e.g., "Blue Whale" -> "Blue_Whale")
    clean_name <- row$Name

    #match to metrics
    mrow <- model.metrics[which(model.metrics$Common.Name == row$Common.Name),]

    ##get list of variables from guilds
    fList <- feeding_key[,which(names(feeding_key) == row$Feeding.Guild)]
    fTab <- variable_key[variable_key$Short.Name %in% fList,]
    hList <- habitat_key[,which(names(habitat_key) == row$Habitat.Guild)]
    hTab <- variable_key[variable_key$Short.Name %in% hList,]
    #fhTab <- c(fTab, hTab)

    # 3. Render the report
    quarto::quarto_render(
      input = template,
      output_file = paste0("SDM_Report_", clean_name, ".pdf"),
      execute_params = list(
        species_name = row$Common.Name,
        fGuild = row$Feeding.Guild,
        hGuild = row$Habitat.Guild,
        fTab = as.data.frame(fTab),
        hTab = as.data.frame(hTab),
        n_pres       = mrow$N.PRESENCE,
        n_abs        = mrow$N.ABSENCE,
        aucWI          = round(mrow$ENS.AUC, digits = 3),
        aucOUT = round(mrow$AUC.2020.2023, digits = 3),
        # Assuming your PDFs follow a naming convention:
        weight_plot_pdf = paste0(file.path(getwd(),clean_name, 'figures'), '/component_model_weights.pdf'),
        imp_plot_pdf = paste0(file.path(getwd(),clean_name, 'figures'), '/variable_importance_radars.pdf'),
        results_pdf  = paste0(file.path(getwd(),clean_name, 'figures'), '/mean_SDM_1993_2019_vert.pdf'),
        resid_hist    = paste0(file.path(getwd(),clean_name, 'figures'), '/histogram_residuals_1993_2019.pdf'),
        resid_map    = paste0(file.path(getwd(),clean_name, 'figures'), '/mean_residuals_1993_2019.pdf')
      )
    )

    #move to final folder
    file.rename(
      from = paste0("SDM_Report_", clean_name, ".pdf"),
      to = file.path(report.path, paste0("SDM_Report_", clean_name, ".pdf"))
    )
  } #end i


} #end function
