#' @title Make Sensitivity Table
#' @description
#' Generates the sensitivity table with final attribute scores, data quality, and distribution of tallies for each species. One table is generated per species and saved in the designated directory. Requires directory to be set up per directions in the package documentation/manual.
#'
#' @param species names of species to produce table for. Must match \code{Stock.Name} in \code{raw_data}
#' @param species_col name of column with species names to help subset data. Should be the same across \code{raw_data}, \code{sensitivity}, and \code{data_quality}
#' @param attribute_names_raw,attribute_names_clean vectors of raw attribute names to help subset \code{sensitivity} and \code{data_quality}, and cleaned up names to use in table
#' @param total_sens_col,certainty_col names of column containing total sensitivity scores and associated certainty in \code{sensitivity}
#' @param raw_data raw data exported from FCVA database, including the column \code{Stock.Name} to subset data to correct species
#' @param sensitivity data.frame with attribute scores and final sensitivity and certainty. Generated from \code{calculate.sensitivity} and \code{sensitivity.bootstrap}. Must include the column \code{Stock.Name} to subset data to correct species
#' @param data_quality data.frame with data quality scores for each attribute and species. Generated by \code{data_quality.score}. Must include the column \code{Stock.Name} to subset data to correct species
#' @param sensitivity TRUE indicates sensitivity attribute scores should be plotted. FALSE indicates exposure factor scores should be plotted
#' @param table_dir file path to folder to save tables in
#'
#' @return No returns. Saves pdf file containing the sensitivity table containing the expert scores, data quality, and overall sensitivity score, with certainty.

make_sensitivity_table <- function(
  species,
  species_col,
  attribute_names_raw,
  attribute_names_clean,
  total_sens_col,
  certainty_col,
  raw_data,
  sensitivity,
  data_quality,
  table_dir
) {
  #raw_data is a data.frame of sensitivity data from the portal - used for tally counts/distribution plot
  #sensitivity - data.frame with attribute scores, overall sensitivity, and certainty
  #data_quality - data.frame of data quality scores for each attribute

  for (x in species) {
    #subset each data.frame
    spRaw <- raw_data[raw_data[, species_col] == x, ] #raw_data
    spSens <- sensitivity[sensitivity[, species_col] == x, ] #sensitivity
    spDQ <- data_quality[data_quality[, species_col] == x, ] #data_quality

    #replace final sensitivity with low/moderate/high/v high
    sens.score <- switch(
      as.character(spSens[total_sens_col]),
      '1' = 'Low',
      '2' = 'Moderate',
      '3' = "High",
      '4' = "Very High"
    )

    #sum tallies (keeping this seperate to help check)
    tally.count <- spRaw %>%
      dplyr::group_by(Attribute.Name) %>%
      dplyr::summarise(
        A = sum(Scoring.Rank1, na.rm = T),
        B = sum(Scoring.Rank2, na.rm = T),
        C = sum(Scoring.Rank3, na.rm = T),
        D = sum(Scoring.Rank4, na.rm = T)
      ) %>%
      dplyr::arrange(Attribute.Name) %>%
      dplyr::rowwise()

    #format for matching/plotting
    plot_data <- tally.count %>%
      dplyr::mutate(
        p = list(
          data.frame(x = c("A", "B", "C", "D"), y = c(A, B, C, D)) %>%
            ggplot2::ggplot(ggplot2::aes(x, y, fill = x)) +
            ggplot2::geom_col(
              show.legend = FALSE,
              width = 0.95,
              color = 'grey25',
              linewidth = 4
            ) +
            ggplot2::scale_fill_manual(
              values = c("green", "yellow", "orange", "red")
            ) +
            ggplot2::theme_void() +
            ggplot2::theme(
              plot.margin = ggplot2::margin(0, 0, 0, 0) # Remove all internal ggplot whitespace
            )
        )
      ) %>%
      dplyr::pull(p)

    #make summary table
    tab <- as.data.frame(cbind(
      t(spSens[, attribute_names_raw]),
      t(spDQ[, attribute_names_raw])
    ))
    tab <- round(tab, 2)
    #clean up
    tab$Attribute.Name <- rownames(tab)
    rownames(tab) <- NULL
    tab <- tab[, c(3, 1, 2)]
    colnames(tab)[2:3] <- c("expert.scores", 'data_quality')
    tab$Attribute.Name <- attribute_names_clean #clean up attribute names for table

    #render the final table
    summary.table <- tab %>%
      dplyr::mutate(dist_chart = "") %>%
      gt::gt() %>%
      #title
      gt::tab_header(
        title = 'Sensitivity',
      ) %>%
      gt::tab_options(
        data_row.padding = gt::px(1) # force minimal padding between rows
      ) %>%
      # Center all text columns
      gt::cols_align(
        align = "center",
        columns = gt::everything()
      ) %>%
      #force plot columns to be bottom aligned
      # Force a specific width so the aspect ratio calculates the height correctly
      gt::cols_width(
        Attribute.Name ~ gt::px(240), # Give the labels enough room
        expert.scores ~ gt::px(60), # Forces all Mean columns to 80px
        data_quality ~ gt::px(60), # Forces all SD columns to 80px
        dist_chart ~ gt::px(120)
      ) %>%
      gt::tab_options(
        heading.padding = gt::px(2), # Tightens space around title
        column_labels.padding = gt::px(2) # Tightens space around Mean/SD labels
      ) %>%
      gt::tab_style(
        style = "vertical-align: bottom !important; line-height: 0; padding-bottom: 0;",
        locations = gt::cells_body(columns = gt::starts_with("dist"))
      ) %>%
      gt::tab_style(
        style = "line-height: 0; padding: 0;", # CSS to remove text-based 'float'
        locations = gt::cells_body(columns = colnames(tab)[-1])
      ) %>%
      #change line style of columns
      #thick borders to distinguish factor names and time/space sections
      gt::tab_style(
        style = gt::cell_borders(
          sides = "right",
          color = "black",
          weight = gt::px(2)
        ),
        locations = gt::cells_body(columns = c('Attribute.Name'))
      ) %>%
      #thinner lines everywhere else
      gt::tab_style(
        style = gt::cell_borders(
          sides = "right",
          color = "grey25",
          weight = gt::px(1)
        ),
        locations = gt::cells_body(columns = c('expert.scores', 'data_quality'))
      ) %>%
      gt::text_transform(
        locations = gt::cells_body(columns = dist_chart),
        fn = function(x) {
          plots <- purrr::map(
            plot_data,
            gt::ggplot_image,
            height = gt::px(40),
            aspect_ratio = 2.5
          )

          # Wrap EACH plot in a bottom-aligned flex container
          purrr::map(
            plots,
            ~ gt::html(as.character(paste0(
              "<div style='display: flex; flex-direction: column; justify-content: flex-end; align-items: center; height: 42px;'>",
              .x,
              "</div>"
            )))
          )
        }
      ) %>%
      gt::cols_label(
        Attribute.Name = "Attribute Name",
        expert.scores = "Expert Score",
        data_quality = "Data Quality",
        dist_chart = "Tally Distribution"
      ) %>%
      #Ensure the vertical-align is still bottom
      gt::tab_style(
        style = "vertical-align: bottom !important; padding-top: 2px; padding-bottom: 0px;",
        locations = gt::cells_body(columns = gt::starts_with("dist"))
      ) %>%
      gt::tab_source_note(
        source_note = gt::html(paste0(
          "<div style='text-align: center; font-size: 18px; width: 100%; font-weight: bold;'>",
          "Total Sensitivity: ",
          sens.score,
          " (",
          spSens[, total_sens_col],
          ") | Certainty: ",
          round(spSens[, certainty_col], 2),
          "</div>"
        ))
      ) %>%
      gt::tab_options(
        # Change the font size (standard is usually 9px or 10px)
        source_notes.font.size = gt::px(18),

        # Align the text to the center
        source_notes.padding = gt::px(6), # Adds space around the text
        table.additional_css = "
      .gt_sourcenote {
        display: flex !important;
        justify-content: center !important;
        align-items: center !important;
        text-align: center !important;
        width: 100% !important;
      }"
      ) %>%
      #add box
      gt::tab_options(
        # Sets a border around the entire table container
        table.border.top.style = "solid",
        table.border.top.width = gt::px(4),
        table.border.top.color = "black",

        table.border.bottom.style = "solid",
        table.border.bottom.width = gt::px(4),
        table.border.bottom.color = "black",

        # These two add the side borders to complete the box
        table.background.color = "white",
        table.additional_css = "
      .gt_table {
        border-left: 4px solid black !important;
        border-right: 4px solid black !important;
      }"
      )

    #save
    gt::gtsave(
      summary.table,
      paste0(table_dir, '/sensitivity_table_', gsub(' ', '', x), '.pdf')
    )
  } #end x
}
