#' @title Match Species Presence-Absence Data Frame to Environmental Data
#' @description
#' Match species data frame and environmental rasters to build data frame for modeling
#'
#' @param species_df A data.frame containing species presence-absence data. 
#' @param model_data  A list containing spatRasters of each environmental variable to be matched, or the output of \code{normalize_model_data} or \code{get_model_data_wrapper}. Each member of the list should have a name which will correspond to the environmental variable's column name in the resulting dataframe. 
#' @param add_static TRUE/FALSE to add static variables such as bathymetry. If TRUE, static_variables needs to be supplied. Note that if the user is supplying normalized dynamic environmental variable that static variables should also be normalized with the same methods. 
#' @param static_variables a spatRaster containing static variables such as bathymetry. Names of each layer will become the column names.
#'
#' @return \code{match_fisheries_environment_data} returns a data frame with the following columns:
#' \itemize{
#' \item \code{x, y, month, year} indicating longitude, latitude, month, and year
#' \item \code{pa} - the column indicating presence, absence, and effort from the fisheries raster
#' \item A number of columns equal to the length of \code{model_data} with the same names containing the corresponding environmental data at each location
#' \item A number of columns equal to the length of \code{static_variables}, if \code{add_static = T}, with column names matching the names of the rasters in the list
#' }
#'
#'@export

match_fisheries_environment_data <- function(
    species_df,
    model_data,
    add_static = TRUE,
    static_variables
) {
  
  #step 1 - prepare rasters
  #we are going to combine all the rasters to limit the number of extract calls so we have to prepare them accordingly 
  #pull each spatRaster and append variable name
  combined_stack <- NULL
  for (x in 1:length(model_data)) {
    v <- names(model_data)[x] #isolate one environmental variable name
    names(model_data[[x]]) <- paste(v, names(model_data[[x]]), sep = '_')
    combined_stack <- c(model_data[[x]], combined_stack)
  } #end x 
  
  #step 2 - extract the unique locations within pa_species
  unique_locs_df <- unique(species_df[, c("gridID", "grid.lon", "grid.lat")])
  unique_locs_v  <- terra::vect(unique_locs_df, geom = c("grid.lon", "grid.lat"), crs = "EPSG:4326")
  
  # Extract everything in one single spatial pass
  extracted_wide <- terra::extract(combined_stack, unique_locs_v, ID = TRUE)
  
  # Merge the spatial IDs back with your location metadata
  extracted_wide_meta <- cbind(unique_locs_df, extracted_wide)
  
  #remove any grid cells with NAs - meaning that they were over land - to help speed up reshape
  extracted_wide_meta <- extracted_wide_meta[complete.cases(extracted_wide_meta),]
  
  # 4. Reshape from wide to long format using base R's reshape()
  # This looks for the "_" delimiter we created in step 1
  extracted_long <- reshape(
    extracted_wide_meta,
    idvar = c("gridID", "grid.lon", "grid.lat", "ID"), # Columns that uniquely identify the location
    varying = 5:ncol(extracted_wide_meta),    # The columns containing the extracted raster data
    direction = "long",
    sep = "_",                                # Splits "temp_7.2026" into time and variable
    timevar = "month.year"                     # Name of the new time column
  )
  
  # Clean up rownames generated by reshape()
  rownames(extracted_long) <- NULL
  
  # 5. Merge the results back into your original observation data.frame
  species_df$month.year <- paste(species_df$month, species_df$year, sep = '.')
  fish_env_df <- merge(
    species_df, 
    extracted_long[, c("gridID", "month.year", names(model_data))], 
    by = c("gridID", "month.year"), 
    all.x = TRUE
  )
  
  #remove any grid cells with NAs - meaning that they were over land - again because we've matched to all the observations in species_df
  fish_env_df <- fish_env_df[complete.cases(fish_env_df),]
  
  #add static variables - this one is simpler because the variables don't change through time
  if (add_static) {
    st <- terra::extract(static_variables, fish_env_df[,c("grid.lon", "grid.lat")])
    fish_env_df <- cbind(fish_env_df, st)
  } #end if(add_static)
  
  return(fish_env_df)
} #end function
