#' @title Merge Fisheries Presence/Absence/Effort Rasters
#' @description Combines rasters from \code{create_rast} across multiple sources
#'
#' @param rastList list of outputs from \code{create_rast} to combine
#'
#' @return returns a single rasterBrick with the same spatial and temporal resolution as provided rasters. Maximum value should be 2 to ensure that presences are included.
#'

merge_rasts <- function(rastList){
  #merge rasters generated from multiple data types
  #rastList is a list of rasterStacks generated by create_rast

  #remove null objects in list
  i <- unlist(lapply(rastList,is.null))
  if(length(which(i)) != 0){
    rastList <- rastList[!i]
  }

  rastAll <- vector(mode = 'list', length = raster::nlayers(rastList[[1]]))
  for(x in 1:raster::nlayers(rastList[[1]])){
    rs <- raster::stack(lapply(rastList, FUN = function(y){subset(y, x)}))
    rastAll[[x]] <- raster::calc(rs, max)
  }
  rastAll <- raster::brick(rastAll)
  raster::extent(rastAll) <- raster::extent(rastList[[1]])
  sp::proj4string(rastAll) <- sp::CRS('+proj=longlat +datum=WGS84 +no_defs')
  names(rastAll) <- names(rastList[[1]])
  return(rastAll)

}
