#' @title Merge Fisheries Presence/Absence/Effort Rasters
#' @description Combines rasters from \code{create_rast} across multiple sources
#'
#' @param raster_list list of outputs from \code{create_rast} to combine
#'
#' @return returns a single rasterBrick with the same spatial and temporal resolution as provided rasters. Maximum value should be 2 to ensure that presences are included.
#'

merge_fisheries_rasters <- function(raster_list){
  #merge rasters generated from multiple data types
  #raster_list is a list of rasterStacks generated by create_rast

  #remove null objects in list
  i <- unlist(lapply(raster_list,is.null))
  if(length(which(i)) != 0){
    raster_list <- raster_list[!i]
  }

  rastAll <- vector(mode = 'list', length = raster::nlayers(raster_list[[1]]))
  for(x in 1:raster::nlayers(raster_list[[1]])){
    rs <- raster::stack(lapply(raster_list, FUN = function(y){subset(y, x)}))
    rastAll[[x]] <- raster::calc(rs, max)
  }
  rastAll <- raster::brick(rastAll)
  raster::extent(rastAll) <- raster::extent(raster_list[[1]])
  sp::proj4string(rastAll) <- sp::CRS('+proj=longlat +datum=WGS84 +no_defs')
  names(rastAll) <- names(raster_list[[1]])
  return(rastAll)

}
