#' @title Sensitivity Functions 
#' @description Functions to calculate sensitivity, and perform bootstrap analysis from expert scores. These functions were based on code from the Southeast Fisheries Science Center (SEFSC) and Highly Migratory Species (HMS) Climate Vulnerability Assessment Analysis. 
#' 
#' \itemize{
#' \item \code{attribute.score} calculates the weighted average sensitivity score per the methods in Morrison et al 2015, using the number of tallies in each bin, with higher vulnerabilities receiving a higher weight. The score is calculated for all attributes and across all experts. The option to perform a bootstrap analysis is provided; output format changes depending on if the bootstrap is performed. 
#' \item \code{logic rule} uses the logic rule from Hare et al 2016 to calculate an overall sensitivity score for each species. User must specify if the provided data is from a bootstrap analysis, as the required inputs change depending on if the bootstrap is performed. 
#' \item \code{calculate.sensitivity} is a wrapper function for \code{attribute.score} and \code{logic.rule} to perform the complete calculation. Output depends on if bootstrap is performed. 
#' \item \code{bootstrap.certainty} calculates the certainty around bootstrap estimates from \code{calculate.sensitivity(bootstrap = TRUE)}. See details for more information. 
#' }
#' 
#' @param species.attributes a list of data frames, with each data frame corresponding to all of the expert scores for one species. See example for how to generate this list. 
#' @param bootstrap binary TRUE/FALSE to turn on/off bootstrapping of sensitivity scores. Will impact outputs. 
#' @param samples number of samples to run for bootstrapping. Default is 10,000.
#' @param attribute a list of data frames, with each data frame consisting of all expert scores for a single sensitivity attribute and species. Generated by \code{calculate.sensitivity}. 
#' @param attribute.vec output from \code{attribute.score}
#' @param species.bootstrap output from \code{calculate.sensitivity(bootstrap = TRUE)}
#' @param match binary TRUE/FALSE to match bootstrap certainty (percentage of bootstrapped scores that match weighted averaged score) to output from \code{calculate.sensitivity(bootstrap = FALSE)}
#' @param sensitivity.dataframe The output from \code{calculate.sensitivity(bootstrap = FALSE)} to append bootstrap certainty to. Must be provided if \code{match = TRUE}. 
#' 
#' @return \code{calculate.sensitivity} returns a data.frame where each row is a species, and columns represent attribute scores, as well as the total sensitivity score returned by the logic rule
#' @return \code{attribute.score} returns weighted averaged scores for each attribute. If \code{bootstrap = TRUE}, this is a data frame with the number of rows equal to the number of samples, and the number of columns equal to the number of attributes. If \code{bootstrap = FALSE}, this is a vector equal to the length of the number of attributes. 
#' @return \code{logic.rule} returns the final sensitivity scores based on the logic rule. The output is similar to \code{attribute.score}, where if \code{bootstrap = TRUE}, the function returns a vector containing the final sensitivity score for each sample, and if \code{bootstrap = FALSE}, it returns a single final value. 
#' @return \code{bootstrap.certainty} returns a data.frame or a vector. If \code{match = TRUE}, it returns the \code{sensitivity.dataframe} with a new column called 'Certainty', which includes the percentage of bootstrapped sensitivities that matched the weighted average final sensitivity. If \code{match = FALSE}, it returns a vector containing what percent of bootstrapped values were equal to each possible sensitivity score (1-4).   

calculate.sensitivity <- function(species.attributes, bootstrap = TRUE, samples = 10000){
  #species.attributes is a list of dataframes, with one data frame per species
  #bootstrap is boolean TRUE/FALSE to trigger bootstrapping 
  #samples is the number of samples to use in bootstrapping 
  
  #subset by attribute
  attribute.list <- dlply(species.attributes, .(Attribute.Name)) #make list of data frames with one data frame per list
  a.scores <- lapply(attribute.list, attribute.score, bootstrap = bootstrap, samples = samples) #calculate scores for attributes via weighted mean
  out <- do.call(cbind, a.scores) #combine scores into vector
  
  #apply logic rule and add to vector 
  total <- logic.rule(out, bootstrap = bootstrap)
  
  #clean up vector
  sensitivity.attributes <- as.data.frame(cbind(out, total))
  colnames(sensitivity.attributes)[dim(sensitivity.attributes)[2]] <- 'Total Sensitivity'
  return(sensitivity.attributes)
}

attribute.score <- function(attribute, bootstrap = TRUE, samples = 10000){
  scores.only <- attribute[,(dim(attribute)[2]-3):
                             dim(attribute)[2]] #isolate scores
  
  if(bootstrap){ #if bootstrap is TRUE, perform bootstrap
    set.seed(2026)
    scoresB <- NULL
    
    if(sum(scores.only,na.rm = T) == 0){ #check for data (if all are NAs, sum will be equal to 0)
      scoresB <- rep(0, length=samples)
    }else{
      for(i in 1:samples){
        ## from HMS CVA code
        #calculate number of tallies into L, M, H, V
        L<-sum(scores.only$Scoring.Rank1,na.rm=T)
        M<-sum(scores.only$Scoring.Rank2,na.rm=T)
        H<-sum(scores.only$Scoring.Rank3,na.rm=T)
        V<-sum(scores.only$Scoring.Rank4,na.rm=T)
        
        #create draw pile based on number of tallies in each category
        draw_pile<-c(rep(1,L),rep(2,M),rep(3,H),rep(4,V))
        
        #randomly sample with replacement 25 (5 tallies x 5 experts) from draw pile
        samp<-sample(x=draw_pile,size=5 * nrow(scores.only),replace=TRUE) #replaced 5 with 5 * nrow(scores.only)
        
        #table of 1,2,3,4 in samp
        samp.tab<-data.frame(table(samp))
        
        sampL<-ifelse(any(unique(samp)==1),samp.tab$Freq[which(samp.tab$samp==1)],0)
        sampM<-ifelse(any(unique(samp)==2),samp.tab$Freq[which(samp.tab$samp==2)],0)
        sampH<-ifelse(any(unique(samp)==3),samp.tab$Freq[which(samp.tab$samp==3)],0)
        sampV<-ifelse(any(unique(samp)==4),samp.tab$Freq[which(samp.tab$samp==4)],0)
        
        #calculate weighted average
        score<-((sampL*1) + (sampM*2) + (sampH*3) + (sampV*4)) / (nrow(scores.only) * 5) #replaced num.experts with nrow(scores.only)
        scoresB <- c(scoresB, score)
      } #end loop 
    } #end if
    
    return(scoresB)
    
  } else { #if bootstrap if FALSE, just get weighted mean
    score <- (sum(scores.only[,1], na.rm = T) + sum(scores.only[,2], na.rm = T)*2 + sum(scores.only[,3], na.rm = T)*3 + sum(scores.only[4], na.rm = T)*4) / sum(scores.only, na.rm = T)
    #names(score) <- attribute$Attribute.Name
    return(score)
  }
  
}

logic.rule <- function(attribute.vec, bootstrap){
  if(bootstrap){ #if bootstrap = T, attribute.vec will be a MATRIX; apply the logic rule to each ROW 
    total.score <- vector(length = nrow(attribute.vec))
    for(x in 1:nrow(attribute.vec)){
      if(length(which(attribute.vec[x,]>=3.5))>=3){ # Very High 
        total.score[x] <- 4
      }else if(length(which(attribute.vec[x,]>=3))>=2){ # High
        total.score[x] <- 3
      }else if(length(which(attribute.vec[x,]>=2.5))>=2){ # Moderate
        total.score[x] <- 2
      }else{ # Low
        total.score[x] <- 1
      } #end if/elses
    } # end for 
  } else { #if bootstrap == F, attribute.vec will be a vector; apply logic rule to vector only
    total.score <- NULL
    if(length(which(attribute.vec>=3.5))>=3){ # Very High 
      total.score <- 4
    }else if(length(which(attribute.vec>=3))>=2){ # High
      total.score <- 3
    }else if(length(which(attribute.vec>=2.5))>=2){ # Moderate
      total.score <- 2
    }else{ # Low
      total.score <- 1
    } #end if/elses
  }
  
  return(total.score) #same thing to return either way :) 
}

bootstrap.certainty <- function(species.bootstrap, match = T, sensitivity.dataframe){
  #species.bootstrap is the bootstrap matrix that results from calculate.sensitivity(bootstrap=T)
  
  percentages <- vector(length = 4)
  # Go through the data for each species and calculate the portion of scores in each category
  percentages[1] <- length(which(species.bootstrap[,ncol(species.bootstrap)]==1))/nrow(species.bootstrap)
  percentages[2] <- length(which(species.bootstrap[,ncol(species.bootstrap)]==2))/nrow(species.bootstrap)
  percentages[3] <- length(which(species.bootstrap[,ncol(species.bootstrap)]==3))/nrow(species.bootstrap)
  percentages[4] <- length(which(species.bootstrap[,ncol(species.bootstrap)]==4))/nrow(species.bootstrap)
  
  if(match){
    sensitivity.dataframe$Certainty <- 0
    for(x in 1:nrow(sensitivity.dataframe)){
      s <- sensitivity.dataframe$`Total Sensitivity`[x]
      sensitivity.dataframe$Certainty[x] <- certaintyDF[x,s]
      return(sensitivity.dataframe)
    }
  } else {
    return(percentages)
  }
}
